name: boostdevel_cbuild

on:
  push:
    paths:
      - containers/boostdevel/**
      - .github/workflows/boostdevel.yml # Self-trigger

  workflow_run:
    workflows: 
      - cppdevel_cbuild
    branches:
      - main
    types: 
      - completed
      
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: bounverif/boostdevel
  VERSION: latest

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: containers/boostdevel
          build-args: "VERSION=${{ env.VERSION }}"
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
